### ISSUE TITLE
Gaze Values

### ISSUE THREAD

**Issue by dsnsabari** [david-wb/gaze-estimation#4]
Could you tell me how we can use this gaze values to tell the person looking direction? when I compared the model gaze values and training data gaze it looks quite different. from the vector, gaze value has arrived but how we can use that tell the person looking direction?

**Comment by david-wb** [comment]
The gaze value is the yaw/pitch angles. A yaw and pitch of zero would be looking directly at the camera. A yaw of 45 degrees is looking left or right at 45 degrees off the camera Z-axis. 

Hope that helps.

**Comment by dsnsabari** [comment]
thank you for the explanation.

**Comment by qhanson** [comment]
> The gaze value is the yaw/pitch angles. A yaw and pitch of zero would be looking directly at the camera. A yaw of 45 degrees is looking left or right at 45 degrees off the camera Z-axis.
> 
> Hope that helps.

Do you know what the yaw of 45 degress indicate either looking left or right 45 degress off the camera Z-axis?
