### ISSUE TITLE
Reference Paper

### ISSUE THREAD

**Issue by lghasemzadeh** [david-wb/gaze-estimation#7]
Hello Davis,

Would you please share the reference paper to this gaze-estimation work?
I have these references:

https://ait.ethz.ch/projects/2018/landmarks-gaze/downloads/park2018etra.pdf
https://www.cl.cam.ac.uk/research/rainbow/projects/unityeyes/
https://rahimentezari.github.io/GAN/gan-gaze.html
https://openaccess.thecvf.com/content_ICCV_2019/papers/He_Photo-Realistic_Monocular_Gaze_Redirection_Using_Generative_Adversarial_Networks_ICCV_2019_paper.pdf
https://openaccess.thecvf.com/content_cvpr_2018/papers/Wang_A_Hierarchical_Generative_CVPR_2018_paper.pdf
https://www.mdpi.com/1424-8220/20/17/4935/htm

But I need the exact reference to the GAN part.

I actually tested the first link which you mentioned is the base to this work several months ago and the performance was not satisfying and there was lag in the stream and the detection. I want to know exactly what improvement/development/modification made to this [work](https://ait.ethz.ch/projects/2018/landmarks-gaze/downloads/park2018etra.pdf) which became this [one](https://github.com/david-wb/gaze-estimation).

Waiting for your response.

Thx,

**Comment by david-wb** [comment]
Hi @lghasemzadeh, 

This project was completely based on https://ait.ethz.ch/projects/2018/landmarks-gaze/downloads/park2018etra.pdf. 

I did not use GANs at all. The training data is generated using UnityEyes.

Hope that helps,
David

**Comment by lghasemzadeh** [comment]
Hi David,

Would you please explain what improvement/development/modification you made to this work:
https://ait.ethz.ch/projects/2018/landmarks-gaze/downloads/park2018etra.pdf.

As I mentioned I had tried that algorithm (the reference one) several months ago and its performance is a bit different from what you provided in your repo.

I want to know the differences between the reference one and this work you provided. Are they completely the same in methodology?

Thank you
